
package guitest;

import javax.swing.JFrame;

/**
 *
 * @author riost02
 */
public class MainMenuWindow extends javax.swing.JFrame {
    
    private RecipeBox collection;

    /**
     * Creates new form MainMenu
     */
    public MainMenuWindow() {
        //Set frame's title
        setTitle("Recipe Manager");
        //Setting the windows size
        pack();                            //Resizing app windows components
        setSize(750,600);
        initComponents();
        collection = new RecipeBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        title = new javax.swing.JLabel();
        addRecipeButton = new javax.swing.JButton();
        editRecipeButton = new javax.swing.JButton();
        deleteRecipeButton = new javax.swing.JButton();
        displayRecipeNameInCollectionButton = new javax.swing.JButton();
        displayRecipeButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 450));
        setSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(new java.awt.GridLayout(8, 3));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Recipe Manager");
        getContentPane().add(title);

        addRecipeButton.setText("Add Recipe");
        addRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addRecipeButton);

        editRecipeButton.setText("Edit a recipe");
        editRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRecipeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editRecipeButton);

        deleteRecipeButton.setText("Delete a recipe");
        deleteRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecipeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteRecipeButton);

        displayRecipeNameInCollectionButton.setText("Print all the recipe names in the collection");
        displayRecipeNameInCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRecipeNameInCollectionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayRecipeNameInCollectionButton);

        displayRecipeButton.setText("Print the details of a recipe");
        displayRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRecipeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayRecipeButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayRecipeNameInCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRecipeNameInCollectionButtonActionPerformed
        // Print Recipe Names
        PrintRecipeNamesInCollectionWindow myFrame = new PrintRecipeNamesInCollectionWindow(collection);
        
        /* Window Settings */
        myFrame.pack();                            //Resizing app windows components
        myFrame.setVisible(true);                  //Display window
    }//GEN-LAST:event_displayRecipeNameInCollectionButtonActionPerformed

    private void deleteRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecipeButtonActionPerformed
        // Delete a recipe
        DeleteRecipeWindow myFrame = new DeleteRecipeWindow(collection);
        
        /* Window Settings */
        myFrame.pack();                            //Resizing app windows components
        myFrame.setVisible(true);                  //Display window
    }//GEN-LAST:event_deleteRecipeButtonActionPerformed

    private void addRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButtonActionPerformed
        
        // Creat a new window to create recipe objects
        CreateNewRecipeWindow myFrame = new CreateNewRecipeWindow(collection);
        
        /* Window Settings */
        //myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        myFrame.pack();                            //Resizing app windows components
        myFrame.setVisible(true);                  //Display window
        
    }//GEN-LAST:event_addRecipeButtonActionPerformed

    private void displayRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRecipeButtonActionPerformed
        
        // Creat a new window to create recipe objects
        PrintRecipeDetailsWindow myFrame = new PrintRecipeDetailsWindow(collection);
        
        /* Window Settings */
        //myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        myFrame.pack();                            //Resizing app windows components
        myFrame.setVisible(true);                  //Display window
    }//GEN-LAST:event_displayRecipeButtonActionPerformed

    private void editRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRecipeButtonActionPerformed
        // Creat a new window to create recipe objects
        EditRecipeWindow myFrame = new EditRecipeWindow(collection);
        
        /* Window Settings */
        //myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        myFrame.pack();                            //Resizing app windows components
        myFrame.setVisible(true);                  //Display window
    }//GEN-LAST:event_editRecipeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecipeButton;
    private javax.swing.JButton deleteRecipeButton;
    private javax.swing.JButton displayRecipeButton;
    private javax.swing.JButton displayRecipeNameInCollectionButton;
    private javax.swing.JButton editRecipeButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
